name = "astropal-io"
pages_build_output_dir = ".vercel/output/static"

# Environment variables for production and preview
# The VITE_PUBLIC_ZAPIER_WEBHOOK_URL secret is managed through Cloudflare Pages dashboard
[env.production]

[env.preview] 