# Cloudflare Pages configuration for Astropal.io
name = "astropal-io"
compatibility_date = "2024-01-01"

# Pages build configuration
pages_build_output_dir = "dist"

[build]
command = "./cloudflare-build.sh"
cwd = ""
watch_dir = "apps/web"

[build.environment_variables]
NODE_VERSION = "18" 