name = "astropal-io" 
pages_build_output_dir = ".vercel/output/static"

# Environment variables are managed through Cloudflare Pages dashboard
# No binding needed in wrangler.toml for Pages Functions 