name = "astropal-io" 
pages_build_output_dir = ".vercel/output/static"

# Environment variables are managed through Cloudflare Pages dashboard as **Secrets**.
# No binding is required here for Pages Functions.
 