# Cloudflare Pages configuration for Astropal.io

[build]
command = "./cloudflare-build.sh"
cwd = ""
watch_dir = "apps/web"

[build.environment_variables]
NODE_VERSION = "18"

[env.production]
name = "astropal-io"
compatibility_date = "2024-01-01"

[env.preview]  
name = "astropal-io-preview"
compatibility_date = "2024-01-01" 