import React from 'react';
import { Star } from 'lucide-react';

const Terms: React.FC = () => {
  return (
    <div className="bg-black text-white min-h-screen">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between p-6">
        <div className="flex items-center space-x-2">
          <Star className="w-5 h-5" />
          <span className="font-mono text-sm">ASTROPAL</span>
        </div>
      </nav>

      <div className="pt-24 pb-16 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-xs text-gray-500 font-mono mb-8">[ TERMS OF SERVICE ]</div>
          <h1 className="text-4xl md:text-6xl font-light mb-12">Terms of Service</h1>
          
          <div className="space-y-8 text-gray-300 leading-relaxed">
            <p className="text-sm text-gray-400">Effective Date: January 1, 2025</p>
            
            <section>
              <h2 className="text-xl font-medium text-white mb-4">Acceptance of Terms</h2>
              <p>By accessing or using Astropal's services, you agree to be bound by these Terms of Service. If you do not agree to all terms, do not use our services.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Eligibility</h2>
              <p>You must be at least 18 years old and have legal capacity to enter binding agreements. By using our services, you represent that you meet these requirements.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Service Description</h2>
              <div className="space-y-3">
                <p>Astropal provides personalized cosmic newsletters featuring:</p>
                <ul className="space-y-1 list-disc list-inside ml-4">
                  <li>Daily astrological guidance based on your birth chart</li>
                  <li>Numerological insights and spiritual wellness content</li>
                  <li>Tarot, crystal, chakra, and feng shui guidance</li>
                  <li>Cosmic timing recommendations</li>
                </ul>
                <p className="text-yellow-400 font-medium">Content is delivered via email only and generated by advanced algorithms.</p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Entertainment Purposes Only</h2>
              <div className="bg-gray-900/50 border border-gray-800 rounded-lg p-4 space-y-3">
                <p className="text-yellow-400 font-medium">IMPORTANT DISCLAIMER:</p>
                <p><strong className="text-white">All content is for entertainment purposes only.</strong> Our services do not provide medical, financial, legal, relationship, or professional advice. We make no guarantees about accuracy or outcomes from following our guidance.</p>
                <p>All content is generated by artificial intelligence and may contain errors or inconsistencies.</p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">User Responsibilities</h2>
              <div className="space-y-3">
                <p><strong className="text-white">You agree to:</strong></p>
                <ul className="space-y-1 list-disc list-inside ml-4">
                  <li>Provide accurate birth and personal information</li>
                  <li>Use services only for personal, non-commercial purposes</li>
                  <li>Maintain confidentiality of your account credentials</li>
                  <li>Comply with all applicable laws</li>
                </ul>
                <p><strong className="text-white">Prohibited activities:</strong> Sharing or reselling content, using automated systems, creating multiple accounts, or any illegal activities.</p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Payment & Subscription</h2>
              <ul className="space-y-2 list-disc list-inside">
                <li>Subscription fees are billed in advance and are non-refundable</li>
                <li>You may cancel anytime; cancellation takes effect at period end</li>
                <li>Failed payments may result in service suspension</li>
                <li>Prices may change with advance notice</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Intellectual Property</h2>
              <p>All content, software, algorithms, and branding are protected by intellectual property laws. You may not reproduce, distribute, or create derivative works without permission.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Limitation of Liability</h2>
              <div className="bg-gray-900/50 border border-gray-800 rounded-lg p-4 space-y-3">
                <p className="text-white font-medium">TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
                <ul className="space-y-1 list-disc list-inside">
                  <li>We are not liable for decisions made based on our content</li>
                  <li>Our total liability shall not exceed amounts paid in the last 12 months</li>
                  <li>We exclude liability for indirect, consequential, or punitive damages</li>
                  <li>You assume all risks from using our entertainment services</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Service Availability</h2>
              <p>We do not guarantee continuous service availability. Services may be modified, suspended, or discontinued at any time without notice.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Termination</h2>
              <p>We may terminate your account for violations of these terms, non-payment, or any reason at our discretion. Upon termination, access ends immediately and data may be permanently deleted.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Dispute Resolution</h2>
              <p>Any disputes shall be resolved through binding arbitration rather than court proceedings. You waive rights to class action lawsuits.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Changes to Terms</h2>
              <p>We may update these terms at any time. Material changes will be communicated via email. Continued use after changes constitutes acceptance.</p>
            </section>

            <section>
              <h2 className="text-xl font-medium text-white mb-4">Contact Information</h2>
              <p>
                For questions about these Terms of Service, contact us at{' '}
                <a href="mailto:support@astropal.io" className="text-gray-400 hover:text-white transition-colors">
                  support@astropal.io
                </a>
              </p>
            </section>
          </div>

          <div className="mt-16 text-center">
            <a 
              href="/"
              className="inline-block px-8 py-3 bg-white text-black hover:bg-gray-200 transition-colors font-medium"
            >
              RETURN HOME
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Terms;